'''
Create a calculator capable of performing addition, subtraction, 
multiplication and division operations on two numbers. 
Your program should format the output in a readable manner!
'''


number1 = 50
number2 = 3

# Calculater
print("Welcome to calculater.\n")
print ("Here we are using ", number1, " and ", number2, " as number1 and number2 rispectively.\n")
# Addition
print("Addition of number1 and number2 is: ", number1 + number2)

# Subtraction
print("\nSubtraction of number1 and number2 is: ", number1 - number2)

# Multiplication
print("\nMultiplication of number1 and number2 is: ", number1 * number2)

# Division
print("\nDivision of number1 and number2 is: ", number1 / number2)



